version: "3.1"
services:
  app:
    build: .
    container_name: delta
    links:
      - redis
    env_file: ./.env
    environment:
      "NODE_ENV": "production"
    ports:
      - "3001:3000"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6378:6379"